language: ruby
rvm:
  - 1.9.3
  - 2.0.0

services: mongodb

gemfile:
  - Gemfile
  - Gemfile.rails4

before_script:
  - mysql -e 'create database sorcery_test;'

script:
  - "SORCERY_ORM=active_record bundle exec rake spec SPEC=spec/active_record"
  - "SORCERY_ORM=mongoid bundle exec rake spec SPEC=spec/mongoid"
  - "SORCERY_ORM=mongo_mapper bundle exec rake spec SPEC=spec/mongo_mapper"
  - "SORCERY_ORM=datamapper bundle exec rake spec SPEC=spec/datamapper"
